app/home/__init__.py
from flask import Blueprint, render_template
from app.auth import login_required

bp = Blueprint('index', __name__)


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    """
    Menu page
    """
    return render_template('index.html', title='Home')

app/report/__init__.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, flash, request, current_app, abort
from app.forms import ReportForm, GetReportsForm, GetMonthlyReportsForm
from app.models import Report, Teacher
from app.auth import login_required, admin_required
from app import db, excel
from sqlalchemy import and_, or_
from datetime import datetime
import calendar

bp = Blueprint('report_bp', __name__)
app = current_app


@bp.route('/report/form', methods=['GET', 'POST'])
@login_required
def submit_report():
    """
    Create and submit report
    """
    form = ReportForm()
    form.main_teacher.choices = Teacher.get_teachers_for_choices()
    form.assistant_teacher.choices = Teacher.get_teachers_for_choices()
    form.submitted_by.choices = Teacher.get_teachers_for_choices()

    if form.validate_on_submit():
        report = Report(
            main_teacher_id=form.main_teacher.data,
            assistant_teacher_id=form.assistant_teacher.data,
            teaching_date=form.teaching_date.data,
            teaching_content=form.teaching_content.data,
            student_attendance=form.student_attendance.data,
            submitted_by_id=form.submitted_by.data
        )
        db.session.add(report)
        db.session.commit()
        flash(message='Report is successfully submitted.', category='success')
        return redirect(url_for('index.index'))

    return render_template('report/report_submit.html', title='Submit a Report', form=form)


@bp.route('/report/<id>', methods=['GET', 'DELETE'])
@admin_required
def get_or_delete_on_report(id):
    """
    Get or delete a report
    """
    report = Report.query.get(id)

    if request.method == 'DELETE' and request.is_xhr:
        db.session.delete(report)
        db.session.commit()
        flash(message='Report is deleted successfully.', category="success")
        return jsonify({'message': 'Report is deleted.'}), 200

    return render_template('report/report_detail.html', title="Report Detail", report=report)


@bp.route('/report')
@admin_required
def get_reports():
    """
    Get report for specified date period
    """
    form = GetReportsForm(formdata=request.args)
    form.teacher.choices = Teacher.get_teachers_for_choices(
        defaultOpt=(0, 'All'))

    if len(list(request.args.keys())) > 0 and request.is_xhr:
        form.validate()
        result = {'data': {}}
        page = request.args.get('page', 1, type=int)

        if len(form.teacher.errors) == 0 \
                or len(form.from_date.errors) == 0 \
                or len(form.to_date.errors) == 0:
            from_date = form.from_date.data
            to_date = form.to_date.data
            teacher_id = form.teacher.data

            if teacher_id == 0:
                search_type = 'ALL'
                reports = Report.query.filter(
                    and_(
                        Report.teaching_date >= from_date,
                        Report.teaching_date <= to_date
                    )
                ).order_by(Report.teaching_date.desc())
                result['data']['total_reports'] = reports.count()

            else:
                search_type = 'BY_TEACHER'
                reports = Report.query.filter(
                    and_(
                        Report.teaching_date >= from_date,
                        Report.teaching_date <= to_date,
                        or_(
                            Report.main_teacher_id == teacher_id,
                            Report.assistant_teacher_id == teacher_id
                        )
                    )
                ).order_by(Report.teaching_date.desc())
                result['data']['teacher_attendance'] = reports.count()
                result['data']['day_as_main'] = len(list(filter(
                    lambda report: report.main_teacher_id == form.teacher.data, reports)))
                result['data']['day_as_assistant'] = len(list(filter(
                    lambda report: report.assistant_teacher_id == form.teacher.data, reports)))

            paginated_reports = reports.paginate(
                page, app.config['REPORTS_PER_PAGE'], False)

            result['data']['search_type'] = search_type
            result['data']['reports'] = [report.to_dict()
                                         for report in paginated_reports.items]
            result['next_page_num'] = paginated_reports.next_num if paginated_reports.has_next else None

        result['errors'] = {
            'teacher_errors': form.teacher.errors,
            'from_date_errors': form.from_date.errors,
            'to_date_errors': form.to_date.errors
        }

        result['number_of_errors'] = len(form.teacher.errors) + \
            len(form.from_date.errors) + \
            len(form.to_date.errors)

        return jsonify(result)

    return render_template('report/get_reports.html', title='Get Reports', form=form)


@bp.route('/report/get-csv')
@admin_required
def get_report_csv():
    from_date = request.args.get('from_date')
    to_date = request.args.get('to_date')

    reports = Report.query.filter(
        and_(Report.teaching_date >= from_date, Report.teaching_date <= to_date)).all()
    column_names = ['teaching_date', 'main_teacher', 'assistant_teacher',
                    'teaching_content', 'student_attendance', 'submitted_by']
    file_name = f'{from_date} - {to_date}'
    return excel.make_response_from_query_sets(reports, column_names, file_type='csv', file_name=file_name)


@bp.route('/report/delete')
@admin_required
def delete_reports():
    from_date = request.args.get('from_date')
    to_date = request.args.get('to_date')

    try:
        Report.query.filter(and_(Report.teaching_date >= from_date,
                                 Report.teaching_date <= to_date)).delete()
        db.session.commit()
        return jsonify({'message': 'Successfully delete reports.'})
    except:
        return jsonify({'message': 'Failed to delete reports.'}), 500


@bp.route('/report/monthly-report', methods=['GET', 'POST'])
@admin_required
def get_monthly_report():
    form = GetMonthlyReportsForm()
    form.teacher.choices = Teacher.get_teachers_for_choices(
        defaultOpt=(0, 'All'))

    if form.validate_on_submit():
        monthly_report_list = [['Teacher', 'Days as main teacher',
                                'Days as assistant teacher', 'Total days', 'Salary']]

        month = int(form.month.data)
        year = int(form.year.data)
        pay_per_day = int(form.pay_per_day.data)

        if form.teacher.data != 0:
            teachers = Teacher.query.filter_by(id=form.teacher.data)
        else:
            teachers = Teacher.query.all()

        num_days_in_month = calendar.monthrange(year, month)[1]
        start_date = datetime(year, month, 1).date()
        end_date = datetime(year, month, num_days_in_month).date()

        for teacher in teachers:
            report_row = []
            report_row.append(teacher.teacher_name)
            days_as_main = Report.query.filter(
                and_(
                    Report.teaching_date >= start_date,
                    Report.teaching_date <= end_date,
                    Report.main_teacher_id == teacher.id
                )
            ).count()
            days_as_assistant = Report.query.filter(
                and_(
                    Report.teaching_date >= start_date,
                    Report.teaching_date <= end_date,
                    Report.assistant_teacher_id == teacher.id
                )
            ).count()
            total_teaching_days = days_as_main + days_as_assistant
            salary = pay_per_day * total_teaching_days
            report_row.append(days_as_main)
            report_row.append(days_as_assistant)
            report_row.append(total_teaching_days)
            report_row.append(salary)
            monthly_report_list.append(report_row)
        return excel.make_response_from_array(
            monthly_report_list, file_type='csv', file_name=f'{month}-{year} monthly report'
        )

    return render_template('report/get_monthly_report.html', title='Get Monthly Report', form=form)

app/teacher/__init__.py
from flask import Blueprint, redirect, url_for, request, jsonify, render_template, flash, current_app
from app import db
from app.models import Teacher
from app.forms import AddTeacherForm
from app.auth import admin_required

bp = Blueprint('teacher_bp', __name__)
app = current_app


@bp.route('/teacher/add', methods=['GET', 'POST'])
@admin_required
def add_teacher():
    """
    Add new teacher
    """
    form = AddTeacherForm()

    if form.validate_on_submit():
        teacher = Teacher(teacher_name=form.teacher_name.data)
        db.session.add(teacher)
        db.session.commit()
        flash(message='Teacher is successfully added.', category='success')
        return redirect(url_for('teacher.add_teacher'))

    return render_template('teacher/add_teacher.html', title='Add Teacher', form=form)


@bp.route('/teacher')
@admin_required
def get_teachers():
    """
    Get list of teachers
    """
    teachers = Teacher.query.all()

    return render_template('teacher/teachers_list.html', title='Teachers List',
                           teachers=teachers)


@bp.route('/teacher/<teacher_id>/', methods=['PATCH'])
@admin_required
def update_teacher_name(teacher_id):
    """
    Update teacher name
    """
    teacher = Teacher.query.get(int(teacher_id))
    db.session.add(teacher)

    if not request.form['teacher_name']:
        return jsonify({'error': 'Teacher name is required.'})

    teacher.teacher_name = request.form['teacher_name']
    db.session.commit()
    message = f'Successfully update to {request.form["teacher_name"]}.'

    return jsonify({'message': message})


@bp.route('/teacher/<teacher_id>/set-active')
@admin_required
def set_teacher_active(teacher_id):
    """
    Set teacher active
    """
    teacher = Teacher.query.get(int(teacher_id))
    db.session.add(teacher)
    teacher.is_active = True
    db.session.commit()
    message = f'Successfully set {teacher.teacher_name} active.'

    return jsonify({'message': message})


@bp.route('/teacher/<teacher_id>/set-inactive')
@admin_required
def set_teacher_inactive(teacher_id):
    """
    Set teacher inactive
    """
    teacher = Teacher.query.get(int(teacher_id))
    db.session.add(teacher)
    teacher.is_active = False
    db.session.commit()
    message = f'Successfully set {teacher.teacher_name} inactive.'

    return jsonify({'message': message})

app/templates/_flash_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
		{% for category, message in messages %}
			<div class="alert alert-{{ category }}">{{ message }}</div>
		{% endfor %}
	{% endif %}
{% endwith %}

app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}{% endblock %}</title>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
		<script src="https://kit.fontawesome.com/a94141069c.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<script type=text/javascript>
			$SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
		</script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light">
		  <a class="navbar-brand" href="{{ url_for('index.index') }}">TeacherHub</a>
		  {% if g.user %}
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item ">
				<a class="nav-link" href="{{ url_for('index.index') }}">Home</a>
			  </li>
			  <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				  Report
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				  <a class="dropdown-item" href="{{ url_for('report_bp.submit_report') }}">Submit a report</a>
				  <a class="dropdown-item" href="{{ url_for('report_bp.get_reports') }}">Get reports</a>
				  <a class="dropdown-item" href="{{ url_for('report_bp.get_monthly_report') }}">Get monthly report</a>
				</div>
			  </li>
			  <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				  Teacher
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				  <a class="dropdown-item" href="{{ url_for('teacher_bp.add_teacher') }}">Add teacher</a>
				  <a class="dropdown-item" href="{{ url_for('teacher_bp.get_teachers') }}">Teachers list</a>
				</div>
			  </li>
			  {% if g.user.is_admin %}
			  <li class="nav-item ">
				<a class="nav-link" href="{{ url_for('admin.index') }}">Admin</a>
			  </li>
			  {% endif %}
			  <li class="nav-item ">
				<a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
			  </li>
			</ul>
		  </div>
		  {% endif %}
		</nav>
		<div class="container my-5">
		{% block content %}
		{% endblock %}
		</div>
		<footer></footer>
	</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
 
{% block title %}{{ title }}{% endblock %} 

{% block content %}
<h1 class="text-center">{{ title }}</h1>
{% include '_flash_messages.html' %}
<div class="list-group py-4 text-center">
  <h3 class="list-group-item active">Report</h3>
  <a
    class="list-group-item list-group-item-action"
    href="{{ url_for('report_bp.submit_report') }}"
  >
    Submit A Report
  </a>
  <a
    class="list-group-item list-group-item-action"
    href="{{ url_for('report_bp.get_reports') }}"
  >
    Get Reports
  </a>
  <a
    class="list-group-item list-group-item-action"
    href="{{ url_for('report_bp.get_monthly_report') }}"
  >
    Get Monthly Report
  </a>
</div>
<div class="list-group py-4 text-center">
  <h3 class="list-group-item active">Teacher</h3>
  <a
    class="list-group-item list-group-item-action"
    href="{{ url_for('teacher_bp.add_teacher') }}"
    >Add Teacher</a
  >
  <a
    class="list-group-item list-group-item-action"
    href="{{ url_for('teacher_bp.get_teachers') }}"
    >Teacher List</a
  >
</div>
{% if g.user %}
	<div class="text-center py-4">
	  <a class="btn btn-secondary btn-block btn-lg" href="{{ url_for('auth.logout') }}">
	  Logout
	  </a>
	</div>
{% endif %} 
{% endblock %}